# Generated by Django 3.2.9 on 2021-11-03 19:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('director', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('date_released', models.DateField()),
            ],
        ),
    ]
